//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBBase.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Contact
    {
        public int ContactId { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string contents { get; set; }
        public string phone { get; set; }
        public string address { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
    }
}
