//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBBase.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Link
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string Summary { get; set; }
        public string LinkContent { get; set; }
        public string Link { get; set; }
        public string ImagePath { get; set; }
        public string Type { get; set; }
        public Nullable<int> OrderDisplay { get; set; }
        public string Lang { get; set; }
    }
}
