//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBBase.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Pages
    {
        public int PageID { get; set; }
        public string PageName { get; set; }
        public string Link { get; set; }
        public string ImagePath { get; set; }
        public string Summary { get; set; }
        public string PageContent { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<bool> Show { get; set; }
        public string Lang { get; set; }
        public string Keyword { get; set; }
        public string Description { get; set; }
        public string Title { get; set; }
        public Nullable<int> OrderDisplay { get; set; }
    }
}
