//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBBase.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Product
    {
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public string ProductCode { get; set; }
        public string CatalogID { get; set; }
        public string Summary { get; set; }
        public string Content { get; set; }
        public string ImagePath { get; set; }
        public string ImageBigPath { get; set; }
        public Nullable<System.DateTime> DateModify { get; set; }
        public int Store { get; set; }
        public string Promotion { get; set; }
        public string Warranty { get; set; }
        public string Manufacture { get; set; }
        public decimal PriceOld { get; set; }
        public Nullable<decimal> PriceNew { get; set; }
        public int Views { get; set; }
        public int OrderDisplay { get; set; }
        public string Lang { get; set; }
        public bool IsShow { get; set; }
        public bool IsHot { get; set; }
        public bool IsPromotion { get; set; }
        public string Link { get; set; }
        public Nullable<bool> Approve { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> Rating { get; set; }
    }
}
