//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBBase.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_UserPage
    {
        public int id { get; set; }
        public string act { get; set; }
        public string ctrl { get; set; }
        public string Title { get; set; }
        public Nullable<bool> IsShow { get; set; }
        public string Tye { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<int> OrderDisplay { get; set; }
        public string Icon { get; set; }
        public string TypeAction { get; set; }
    }
}
