//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.NGANLUONG_API {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="NS", ConfigurationName="NGANLUONG_API.NGANLUONG_APIPortType")]
    public interface NGANLUONG_APIPortType {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nganluong.vn/public_api.php/checkOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        string checkOrder(string merchant_id, string param, string checksum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nganluong.vn/public_api.php/checkOrder", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        System.Threading.Tasks.Task<string> checkOrderAsync(string merchant_id, string param, string checksum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nganluong.vn/public_api.php/checkOrder_v2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        string checkOrder_v2(string merchant_id, string param, string checksum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nganluong.vn/public_api.php/checkOrder_v2", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        System.Threading.Tasks.Task<string> checkOrder_v2Async(string merchant_id, string param, string checksum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nganluong.vn/public_api.php/registerAffiliateWebsite", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        string registerAffiliateWebsite(string username, string password, string param);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nganluong.vn/public_api.php/registerAffiliateWebsite", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        System.Threading.Tasks.Task<string> registerAffiliateWebsiteAsync(string username, string password, string param);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NGANLUONG_APIPortTypeChannel : Web.NGANLUONG_API.NGANLUONG_APIPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NGANLUONG_APIPortTypeClient : System.ServiceModel.ClientBase<Web.NGANLUONG_API.NGANLUONG_APIPortType>, Web.NGANLUONG_API.NGANLUONG_APIPortType {
        
        public NGANLUONG_APIPortTypeClient() {
        }
        
        public NGANLUONG_APIPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NGANLUONG_APIPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NGANLUONG_APIPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NGANLUONG_APIPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string checkOrder(string merchant_id, string param, string checksum) {
            return base.Channel.checkOrder(merchant_id, param, checksum);
        }
        
        public System.Threading.Tasks.Task<string> checkOrderAsync(string merchant_id, string param, string checksum) {
            return base.Channel.checkOrderAsync(merchant_id, param, checksum);
        }
        
        public string checkOrder_v2(string merchant_id, string param, string checksum) {
            return base.Channel.checkOrder_v2(merchant_id, param, checksum);
        }
        
        public System.Threading.Tasks.Task<string> checkOrder_v2Async(string merchant_id, string param, string checksum) {
            return base.Channel.checkOrder_v2Async(merchant_id, param, checksum);
        }
        
        public string registerAffiliateWebsite(string username, string password, string param) {
            return base.Channel.registerAffiliateWebsite(username, password, param);
        }
        
        public System.Threading.Tasks.Task<string> registerAffiliateWebsiteAsync(string username, string password, string param) {
            return base.Channel.registerAffiliateWebsiteAsync(username, password, param);
        }
    }
}
