//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_EmailTemplate
    {
        public int id { get; set; }
        public string name { get; set; }
        public string template { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
    }
}
