//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Languages
    {
        public string LangKey { get; set; }
        public string LangValue { get; set; }
        public Nullable<int> OrderDisplay { get; set; }
        public Nullable<bool> IsUser { get; set; }
    }
}
