//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Payment
    {
        public int id { get; set; }
        public Nullable<int> InvoiceID { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string PaymentContent { get; set; }
        public string PaymentMenthod { get; set; }
        public string TransactionInfor { get; set; }
        public string TranscactionStatus { get; set; }
        public Nullable<int> Payment_type { get; set; }
        public Nullable<double> Net_amount { get; set; }
        public Nullable<double> Fee_amount { get; set; }
        public Nullable<int> Merchant_id { get; set; }
        public string Customer_name { get; set; }
        public string Customer_email { get; set; }
        public string Customer_phone { get; set; }
    }
}
