//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Post
    {
        public int PostID { get; set; }
        public Nullable<int> CatelogID { get; set; }
        public string PostName { get; set; }
        public string ImagePath { get; set; }
        public string Link { get; set; }
        public string Summary { get; set; }
        public string PostContent { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<bool> IsHot { get; set; }
        public string Lang { get; set; }
        public string Keyword { get; set; }
        public string Description { get; set; }
        public string Title { get; set; }
        public Nullable<int> OrderDisplay { get; set; }
        public Nullable<bool> Approve { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
