//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_UserPermission
    {
        public int id { get; set; }
        public Nullable<int> page_id { get; set; }
        public Nullable<bool> del { get; set; }
        public Nullable<bool> edit { get; set; }
        public Nullable<bool> add { get; set; }
        public Nullable<bool> view { get; set; }
        public string user { get; set; }
    }
}
