//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_UserInfo
    {
        public int InforId { get; set; }
        public string FName { get; set; }
        public string LName { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public Nullable<int> EventId { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Location { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> DateJoin { get; set; }
        public Nullable<System.DateTime> DateRegister { get; set; }
    }
}
