//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_WebInfo
    {
        public int GeneralID { get; set; }
        public string GeneralName { get; set; }
        public string GeneralContent { get; set; }
        public Nullable<System.DateTime> Datemodified { get; set; }
    }
}
