//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Data.Entity.Core.Objects;
using System.Linq;

public partial class Entities : DbContext
{
    public Entities()
        : base("name=Entities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<C_Catalog> C_Catalog { get; set; }
    public virtual DbSet<C_Contact> C_Contact { get; set; }
    public virtual DbSet<C_Email> C_Email { get; set; }
    public virtual DbSet<C_EmailTemplate> C_EmailTemplate { get; set; }
    public virtual DbSet<C_General> C_General { get; set; }
    public virtual DbSet<C_Invoices> C_Invoices { get; set; }
    public virtual DbSet<C_Languages> C_Languages { get; set; }
    public virtual DbSet<C_Link> C_Link { get; set; }
    public virtual DbSet<C_Pages> C_Pages { get; set; }
    public virtual DbSet<C_Payment> C_Payment { get; set; }
    public virtual DbSet<C_Post> C_Post { get; set; }
    public virtual DbSet<C_PostTag> C_PostTag { get; set; }
    public virtual DbSet<C_Product> C_Product { get; set; }
    public virtual DbSet<C_ProductProperty> C_ProductProperty { get; set; }
    public virtual DbSet<C_ProductTag> C_ProductTag { get; set; }
    public virtual DbSet<C_Rating> C_Rating { get; set; }
    public virtual DbSet<C_Role> C_Role { get; set; }
    public virtual DbSet<C_Statistic> C_Statistic { get; set; }
    public virtual DbSet<C_User> C_User { get; set; }
    public virtual DbSet<C_UserInfo> C_UserInfo { get; set; }
    public virtual DbSet<C_UserPage> C_UserPage { get; set; }
    public virtual DbSet<C_UserPermission> C_UserPermission { get; set; }
    public virtual DbSet<C_WebInfo> C_WebInfo { get; set; }
    public virtual DbSet<City> Cities { get; set; }
    public virtual DbSet<DetailOrder> DetailOrders { get; set; }
    public virtual DbSet<District> Districts { get; set; }
    public virtual DbSet<ImageAlbum> ImageAlbums { get; set; }
    public virtual DbSet<ImageProduct> ImageProducts { get; set; }
    public virtual DbSet<Log> Logs { get; set; }
    public virtual DbSet<order> orders { get; set; }
    public virtual DbSet<Showroom> Showrooms { get; set; }

    [DbFunction("Entities", "ConvertDelimitedListIntoTable")]
    public virtual IQueryable<ConvertDelimitedListIntoTable_Result> ConvertDelimitedListIntoTable(string list, string delimiter)
    {
        var listParameter = list != null ?
            new ObjectParameter("list", list) :
            new ObjectParameter("list", typeof(string));

        var delimiterParameter = delimiter != null ?
            new ObjectParameter("delimiter", delimiter) :
            new ObjectParameter("delimiter", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ConvertDelimitedListIntoTable_Result>("[Entities].[ConvertDelimitedListIntoTable](@list, @delimiter)", listParameter, delimiterParameter);
    }

    public virtual ObjectResult<f_Catalog_GetByProductHot_Result> f_Catalog_GetByProductHot(string lang)
    {
        var langParameter = lang != null ?
            new ObjectParameter("Lang", lang) :
            new ObjectParameter("Lang", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<f_Catalog_GetByProductHot_Result>("f_Catalog_GetByProductHot", langParameter);
    }

    public virtual int f_Catalog_GetParent(Nullable<int> catalogID)
    {
        var catalogIDParameter = catalogID.HasValue ?
            new ObjectParameter("CatalogID", catalogID) :
            new ObjectParameter("CatalogID", typeof(int));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("f_Catalog_GetParent", catalogIDParameter);
    }

    public virtual int f_General_Update(string generalName, string generalContent, Nullable<System.DateTime> datemodified, Nullable<bool> show, string lang)
    {
        var generalNameParameter = generalName != null ?
            new ObjectParameter("GeneralName", generalName) :
            new ObjectParameter("GeneralName", typeof(string));

        var generalContentParameter = generalContent != null ?
            new ObjectParameter("GeneralContent", generalContent) :
            new ObjectParameter("GeneralContent", typeof(string));

        var datemodifiedParameter = datemodified.HasValue ?
            new ObjectParameter("Datemodified", datemodified) :
            new ObjectParameter("Datemodified", typeof(System.DateTime));

        var showParameter = show.HasValue ?
            new ObjectParameter("Show", show) :
            new ObjectParameter("Show", typeof(bool));

        var langParameter = lang != null ?
            new ObjectParameter("Lang", lang) :
            new ObjectParameter("Lang", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("f_General_Update", generalNameParameter, generalContentParameter, datemodifiedParameter, showParameter, langParameter);
    }

    public virtual ObjectResult<f_Product_GetByCatalogType_Result> f_Product_GetByCatalogType(string type)
    {
        var typeParameter = type != null ?
            new ObjectParameter("Type", type) :
            new ObjectParameter("Type", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<f_Product_GetByCatalogType_Result>("f_Product_GetByCatalogType", typeParameter);
    }

    public virtual ObjectResult<f_Statistic_All_Result> f_Statistic_All()
    {
        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<f_Statistic_All_Result>("f_Statistic_All");
    }

    public virtual ObjectResult<f_ThongKe_Edit_Result> f_ThongKe_Edit()
    {
        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<f_ThongKe_Edit_Result>("f_ThongKe_Edit");
    }

    public virtual ObjectResult<f_UserInfor_Statistic_Result> f_UserInfor_Statistic()
    {
        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<f_UserInfor_Statistic_Result>("f_UserInfor_Statistic");
    }

    public virtual int f_WebInfo_Update(string generalName, string generalContent, Nullable<System.DateTime> datemodified)
    {
        var generalNameParameter = generalName != null ?
            new ObjectParameter("GeneralName", generalName) :
            new ObjectParameter("GeneralName", typeof(string));

        var generalContentParameter = generalContent != null ?
            new ObjectParameter("GeneralContent", generalContent) :
            new ObjectParameter("GeneralContent", typeof(string));

        var datemodifiedParameter = datemodified.HasValue ?
            new ObjectParameter("Datemodified", datemodified) :
            new ObjectParameter("Datemodified", typeof(System.DateTime));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("f_WebInfo_Update", generalNameParameter, generalContentParameter, datemodifiedParameter);
    }

    public virtual ObjectResult<string> create_order_code()
    {
        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("create_order_code");
    }
}
