//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class C_Catalog
{
    public int CatalogID { get; set; }
    public Nullable<int> ParentID { get; set; }
    public string CategoryName { get; set; }
    public string Link { get; set; }
    public string ImagePath { get; set; }
    public string Intro { get; set; }
    public string MoreInfo { get; set; }
    public string Lang { get; set; }
    public Nullable<bool> Show { get; set; }
    public string Keyword { get; set; }
    public string Description { get; set; }
    public string Title { get; set; }
    public string Type { get; set; }
    public Nullable<int> OrderDisplay { get; set; }
}

public partial class C_Contact
{
    public int ContactId { get; set; }
    public string name { get; set; }
    public string email { get; set; }
    public string contents { get; set; }
    public string phone { get; set; }
    public string address { get; set; }
    public Nullable<System.DateTime> createdate { get; set; }
}

public partial class C_Email
{
    public int id { get; set; }
    public string name { get; set; }
    public string email { get; set; }
    public string phone { get; set; }
    public string address { get; set; }
    public string note { get; set; }
    public Nullable<bool> status { get; set; }
    public Nullable<System.DateTime> createdate { get; set; }
}

public partial class C_EmailTemplate
{
    public int id { get; set; }
    public string name { get; set; }
    public string template { get; set; }
    public Nullable<System.DateTime> createdate { get; set; }
}

public partial class C_General
{
    public int GeneralID { get; set; }
    public string GeneralName { get; set; }
    public string GeneralContent { get; set; }
    public Nullable<System.DateTime> Datemodified { get; set; }
    public Nullable<bool> Show { get; set; }
    public string Lang { get; set; }
}

public partial class C_Invoices
{
    public int id { get; set; }
    public string OrderCode { get; set; }
    public Nullable<System.DateTime> CreateDate { get; set; }
    public string InvoiceContent { get; set; }
    public Nullable<int> Status { get; set; }
}

public partial class C_Languages
{
    public string LangKey { get; set; }
    public string LangValue { get; set; }
    public Nullable<int> OrderDisplay { get; set; }
    public Nullable<bool> IsUser { get; set; }
}

public partial class C_Link
{
    public int ID { get; set; }
    public string Title { get; set; }
    public string Summary { get; set; }
    public string LinkContent { get; set; }
    public string Link { get; set; }
    public string ImagePath { get; set; }
    public string Type { get; set; }
    public Nullable<int> OrderDisplay { get; set; }
    public string Lang { get; set; }
}

public partial class C_Pages
{
    public int PageID { get; set; }
    public string PageName { get; set; }
    public string Link { get; set; }
    public string ImagePath { get; set; }
    public string Summary { get; set; }
    public string PageContent { get; set; }
    public Nullable<System.DateTime> DateModified { get; set; }
    public Nullable<bool> Show { get; set; }
    public string Lang { get; set; }
    public string Keyword { get; set; }
    public string Description { get; set; }
    public string Title { get; set; }
    public Nullable<int> OrderDisplay { get; set; }
}

public partial class C_Payment
{
    public int id { get; set; }
    public Nullable<int> InvoiceID { get; set; }
    public Nullable<double> Amount { get; set; }
    public Nullable<System.DateTime> CreateDate { get; set; }
    public string PaymentContent { get; set; }
    public string PaymentMenthod { get; set; }
    public string TransactionInfor { get; set; }
    public string TranscactionStatus { get; set; }
    public Nullable<int> Payment_type { get; set; }
    public Nullable<double> Net_amount { get; set; }
    public Nullable<double> Fee_amount { get; set; }
    public Nullable<int> Merchant_id { get; set; }
    public string Customer_name { get; set; }
    public string Customer_email { get; set; }
    public string Customer_phone { get; set; }
}

public partial class C_Post
{
    public int PostID { get; set; }
    public Nullable<int> CatelogID { get; set; }
    public string PostName { get; set; }
    public string ImagePath { get; set; }
    public string Link { get; set; }
    public string Summary { get; set; }
    public string PostContent { get; set; }
    public Nullable<System.DateTime> DateModified { get; set; }
    public Nullable<bool> IsHot { get; set; }
    public string Lang { get; set; }
    public string Keyword { get; set; }
    public string Description { get; set; }
    public string Title { get; set; }
    public Nullable<int> OrderDisplay { get; set; }
    public Nullable<bool> Approve { get; set; }
    public Nullable<System.DateTime> CreateDate { get; set; }
}

public partial class C_PostTag
{
    public int PostTagID { get; set; }
    public int PostID { get; set; }
    public string Tag { get; set; }
    public string Link { get; set; }
}

public partial class C_Product
{
    public int ProductID { get; set; }
    public string ProductName { get; set; }
    public string ProductCode { get; set; }
    public string CatalogID { get; set; }
    public string Summary { get; set; }
    public string Content { get; set; }
    public string ImagePath { get; set; }
    public string ImageBigPath { get; set; }
    public Nullable<System.DateTime> DateModify { get; set; }
    public int Store { get; set; }
    public string Promotion { get; set; }
    public string Warranty { get; set; }
    public string Manufacture { get; set; }
    public decimal PriceOld { get; set; }
    public Nullable<decimal> PriceNew { get; set; }
    public int Views { get; set; }
    public int OrderDisplay { get; set; }
    public string Lang { get; set; }
    public bool IsShow { get; set; }
    public bool IsHot { get; set; }
    public bool IsPromotion { get; set; }
    public string Link { get; set; }
    public Nullable<bool> Approve { get; set; }
    public Nullable<System.DateTime> StartDate { get; set; }
    public Nullable<System.DateTime> EndDate { get; set; }
    public Nullable<int> Rating { get; set; }
}

public partial class C_ProductProperty
{
    public Nullable<int> ProductID { get; set; }
    public string Name { get; set; }
    public string Value { get; set; }
    public string Type { get; set; }
    public int ProID { get; set; }
}

public partial class C_ProductTag
{
    public int ProductTagID { get; set; }
    public int ProductID { get; set; }
    public string Tag { get; set; }
    public string Link { get; set; }
}

public partial class C_Rating
{
    public int RatingId { get; set; }
    public Nullable<int> Rating { get; set; }
    public string ip { get; set; }
    public string name { get; set; }
    public string email { get; set; }
    public string contents { get; set; }
    public Nullable<int> itemId { get; set; }
}

public partial class C_Role
{
    public int ID { get; set; }
    public string RoleName { get; set; }
    public string Des { get; set; }
    public string Role { get; set; }
}

public partial class C_Statistic
{
    public int ID { get; set; }
    public System.DateTime ThoiGian { get; set; }
    public long SoTruyCap { get; set; }
    public Nullable<int> year { get; set; }
    public Nullable<int> month { get; set; }
    public Nullable<int> total { get; set; }
}

public partial class C_User
{
    public string Username { get; set; }
    public string Password { get; set; }
    public int Role { get; set; }
    public Nullable<bool> Online { get; set; }
    public Nullable<System.DateTime> LastLogin { get; set; }
    public string IP { get; set; }
}

public partial class C_UserInfo
{
    public int InforId { get; set; }
    public string FName { get; set; }
    public string LName { get; set; }
    public string Phone { get; set; }
    public string Address { get; set; }
    public string Email { get; set; }
    public Nullable<int> EventId { get; set; }
    public Nullable<System.DateTime> Birthday { get; set; }
    public string Location { get; set; }
    public string Note { get; set; }
    public Nullable<System.DateTime> DateJoin { get; set; }
    public Nullable<System.DateTime> DateRegister { get; set; }
}

public partial class C_UserPage
{
    public int id { get; set; }
    public string act { get; set; }
    public string ctrl { get; set; }
    public string Title { get; set; }
    public Nullable<bool> IsShow { get; set; }
    public string Tye { get; set; }
    public Nullable<int> ParentId { get; set; }
    public Nullable<int> OrderDisplay { get; set; }
    public string Icon { get; set; }
    public string TypeAction { get; set; }
}

public partial class C_UserPermission
{
    public int id { get; set; }
    public Nullable<int> page_id { get; set; }
    public Nullable<bool> del { get; set; }
    public Nullable<bool> edit { get; set; }
    public Nullable<bool> add { get; set; }
    public Nullable<bool> view { get; set; }
    public string user { get; set; }
}

public partial class C_WebInfo
{
    public int GeneralID { get; set; }
    public string GeneralName { get; set; }
    public string GeneralContent { get; set; }
    public Nullable<System.DateTime> Datemodified { get; set; }
}

public partial class City
{
    public int CityID { get; set; }
    public string CityName { get; set; }
    public System.DateTime CreateDate { get; set; }
}

public partial class DetailOrder
{
    public int id { get; set; }
    public int OrderID { get; set; }
    public Nullable<int> ProductID { get; set; }
    public string ProductName { get; set; }
    public Nullable<int> Quantity { get; set; }
    public Nullable<double> Price { get; set; }
    public Nullable<double> TotalPrice { get; set; }
    public string Propertices { get; set; }
    public string Code { get; set; }
}

public partial class District
{
    public int DistrictID { get; set; }
    public int CityID { get; set; }
    public string DistrictName { get; set; }
    public System.DateTime CreateDate { get; set; }
}

public partial class ImageAlbum
{
    public int ID { get; set; }
    public Nullable<int> CatalogID { get; set; }
    public string Images { get; set; }
    public string ImagesFull { get; set; }
    public string ImagesName { get; set; }
    public string ImagesDes { get; set; }
}

public partial class ImageProduct
{
    public int ID { get; set; }
    public Nullable<int> MaSP { get; set; }
    public string Images { get; set; }
    public string ImagesFull { get; set; }
}

public partial class Log
{
    public int Id { get; set; }
    public System.DateTime EventDateTime { get; set; }
    public string EventLevel { get; set; }
    public string UserName { get; set; }
    public string MachineName { get; set; }
    public string EventMessage { get; set; }
    public string ErrorSource { get; set; }
    public string ErrorClass { get; set; }
    public string ErrorMethod { get; set; }
    public string ErrorMessage { get; set; }
    public string InnerErrorMessage { get; set; }
}

public partial class order
{
    public int id { get; set; }
    public string Total { get; set; }
    public string Name { get; set; }
    public string LName { get; set; }
    public string Gender { get; set; }
    public string Phone { get; set; }
    public string Fax { get; set; }
    public string Email { get; set; }
    public string City { get; set; }
    public string Address { get; set; }
    public string Recive { get; set; }
    public string Payment { get; set; }
    public string Shipping { get; set; }
    public string Note { get; set; }
    public Nullable<System.DateTime> CreateDate { get; set; }
    public Nullable<bool> Status { get; set; }
    public Nullable<int> Process { get; set; }
    public Nullable<System.DateTime> ShipDate { get; set; }
    public string UserCreate { get; set; }
    public string Code { get; set; }
}

public partial class Showroom
{
    public int ShowroomID { get; set; }
    public int DistrictID { get; set; }
    public string Latitude { get; set; }
    public string Longitude { get; set; }
    public string Name { get; set; }
    public string Phone { get; set; }
    public string Address { get; set; }
    public string Image { get; set; }
    public System.DateTime CreateDate { get; set; }
}

public partial class ConvertDelimitedListIntoTable_Result
{
    public string item { get; set; }
}

public partial class f_Catalog_GetByProductHot_Result
{
    public int CatalogID { get; set; }
    public Nullable<int> ParentID { get; set; }
    public string CategoryName { get; set; }
    public string Link { get; set; }
    public string ImagePath { get; set; }
    public string Intro { get; set; }
    public string MoreInfo { get; set; }
    public string Lang { get; set; }
    public Nullable<bool> Show { get; set; }
    public string Keyword { get; set; }
    public string Description { get; set; }
    public string Title { get; set; }
    public string Type { get; set; }
    public Nullable<int> OrderDisplay { get; set; }
}

public partial class f_Product_GetByCatalogType_Result
{
    public int ProductID { get; set; }
    public string ProductName { get; set; }
    public string ProductCode { get; set; }
    public string CatalogID { get; set; }
    public string Summary { get; set; }
    public string Content { get; set; }
    public string ImagePath { get; set; }
    public string ImageBigPath { get; set; }
    public Nullable<System.DateTime> DateModify { get; set; }
    public int Store { get; set; }
    public string Promotion { get; set; }
    public string Warranty { get; set; }
    public string Manufacture { get; set; }
    public decimal PriceOld { get; set; }
    public Nullable<decimal> PriceNew { get; set; }
    public int Views { get; set; }
    public int OrderDisplay { get; set; }
    public string Lang { get; set; }
    public bool IsShow { get; set; }
    public bool IsHot { get; set; }
    public bool IsPromotion { get; set; }
    public string Link { get; set; }
    public Nullable<bool> Approve { get; set; }
    public Nullable<System.DateTime> StartDate { get; set; }
    public Nullable<System.DateTime> EndDate { get; set; }
    public Nullable<int> Rating { get; set; }
    public Nullable<long> pos { get; set; }
}

public partial class f_Statistic_All_Result
{
    public string year { get; set; }
    public string month { get; set; }
    public Nullable<long> Total { get; set; }
}

public partial class f_ThongKe_Edit_Result
{
    public Nullable<long> HomNay { get; set; }
    public Nullable<long> HomQua { get; set; }
    public Nullable<long> TuanNay { get; set; }
    public Nullable<long> TuanTruoc { get; set; }
    public Nullable<long> ThangNay { get; set; }
    public Nullable<long> ThangTruoc { get; set; }
    public Nullable<long> TatCa { get; set; }
}

public partial class f_UserInfor_Statistic_Result
{
    public Nullable<int> Year { get; set; }
    public Nullable<int> Month { get; set; }
    public Nullable<int> Total { get; set; }
}
