//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImageAlbum
    {
        public int ID { get; set; }
        public Nullable<int> CatalogID { get; set; }
        public string Images { get; set; }
        public string ImagesFull { get; set; }
        public string ImagesName { get; set; }
        public string ImagesDes { get; set; }
    }
}
