//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Web.App_GlobalResources.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký thăm quan.
        /// </summary>
        public static string btnBookingNow {
            get {
                return ResourceManager.GetString("btnBookingNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa.
        /// </summary>
        public static string btnDelete {
            get {
                return ResourceManager.GetString("btnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký.
        /// </summary>
        public static string btnRegister {
            get {
                return ResourceManager.GetString("btnRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi.
        /// </summary>
        public static string btnResetPassword {
            get {
                return ResourceManager.GetString("btnResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu.
        /// </summary>
        public static string btnSave {
            get {
                return ResourceManager.GetString("btnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm kiếm.
        /// </summary>
        public static string btnSearch {
            get {
                return ResourceManager.GetString("btnSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi.
        /// </summary>
        public static string btnSend {
            get {
                return ResourceManager.GetString("btnSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi yêu cầu.
        /// </summary>
        public static string buttonRegister {
            get {
                return ResourceManager.GetString("buttonRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đầu.
        /// </summary>
        public static string FirstPageText {
            get {
                return ResourceManager.GetString("FirstPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuối.
        /// </summary>
        public static string LastPageText {
            get {
                return ResourceManager.GetString("LastPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem tất cả.
        /// </summary>
        public static string linkAll {
            get {
                return ResourceManager.GetString("linkAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết.
        /// </summary>
        public static string linkDetail {
            get {
                return ResourceManager.GetString("linkDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error 403 : Xin lỗi bạn không được phép truy cập.
        /// </summary>
        public static string mess403 {
            get {
                return ResourceManager.GetString("mess403", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error 404: Trang bạn yêu cần không được tìm thấy.
        /// </summary>
        public static string mess404 {
            get {
                return ResourceManager.GetString("mess404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin vui lòng nhập lại mã bảo mật.
        /// </summary>
        public static string messCaptcha {
            get {
                return ResourceManager.GetString("messCaptcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin vui lòng nhập lại mật khẩu.
        /// </summary>
        public static string messConfirmPassword {
            get {
                return ResourceManager.GetString("messConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn cần có ít nhất 2 sản phẩm để so sánh!.
        /// </summary>
        public static string messErrorCompare {
            get {
                return ResourceManager.GetString("messErrorCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin vui lòng thử lại !.
        /// </summary>
        public static string messErrorRegister {
            get {
                return ResourceManager.GetString("messErrorRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa chọn sản phẩm nào !.
        /// </summary>
        public static string messErrorWishlist {
            get {
                return ResourceManager.GetString("messErrorWishlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email này đã được sử dụng.
        /// </summary>
        public static string messExistsEmail {
            get {
                return ResourceManager.GetString("messExistsEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên hoặc mật khẩu đăng nhập của bạn không đúng. Xin vui lòng thử lại..
        /// </summary>
        public static string messLoginFail {
            get {
                return ResourceManager.GetString("messLoginFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký để nhận được đề nghị đặc biệt và chương trình khuyến mãi từ TONYMOLY.
        /// </summary>
        public static string messNewsLetter {
            get {
                return ResourceManager.GetString("messNewsLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy đơn hàng bạn yêu cầu. Xin vui lòng kiểm tra lại..
        /// </summary>
        public static string messOrderNotFound {
            get {
                return ResourceManager.GetString("messOrderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Manor.
        /// </summary>
        public static string mnuAbout {
            get {
                return ResourceManager.GetString("mnuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mẹo làm đẹp.
        /// </summary>
        public static string mnuBeautyTips {
            get {
                return ResourceManager.GetString("mnuBeautyTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spa.
        /// </summary>
        public static string mnuContact {
            get {
                return ResourceManager.GetString("mnuContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mặt bằng.
        /// </summary>
        public static string mnuGallery {
            get {
                return ResourceManager.GetString("mnuGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang chủ.
        /// </summary>
        public static string mnuHome {
            get {
                return ResourceManager.GetString("mnuHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập.
        /// </summary>
        public static string mnuLogin {
            get {
                return ResourceManager.GetString("mnuLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tin tức.
        /// </summary>
        public static string mnuNews {
            get {
                return ResourceManager.GetString("mnuNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại Sản Phẩm.
        /// </summary>
        public static string mnuProduct {
            get {
                return ResourceManager.GetString("mnuProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đào tạo.
        /// </summary>
        public static string mnuRecruitment {
            get {
                return ResourceManager.GetString("mnuRecruitment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký.
        /// </summary>
        public static string mnuRegister {
            get {
                return ResourceManager.GetString("mnuRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khuyến mại.
        /// </summary>
        public static string mnuSaleOff {
            get {
                return ResourceManager.GetString("mnuSaleOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dịch vụ.
        /// </summary>
        public static string mnuService {
            get {
                return ResourceManager.GetString("mnuService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mua hàng.
        /// </summary>
        public static string mnuShopping {
            get {
                return ResourceManager.GetString("mnuShopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiếp.
        /// </summary>
        public static string NextPageText {
            get {
                return ResourceManager.GetString("NextPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hãy nhập ....
        /// </summary>
        public static string placeholderSearch {
            get {
                return ResourceManager.GetString("placeholderSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trước.
        /// </summary>
        public static string PrevPageText {
            get {
                return ResourceManager.GetString("PrevPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ.
        /// </summary>
        public static string strAddress {
            get {
                return ResourceManager.GetString("strAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm vào giỏ.
        /// </summary>
        public static string strAddToCart {
            get {
                return ResourceManager.GetString("strAddToCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tác giả.
        /// </summary>
        public static string strAuthor {
            get {
                return ResourceManager.GetString("strAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trong kho.
        /// </summary>
        public static string strAvailability {
            get {
                return ResourceManager.GetString("strAvailability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bán chạy nhất.
        /// </summary>
        public static string strBestseller {
            get {
                return ResourceManager.GetString("strBestseller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày sinh.
        /// </summary>
        public static string strBirthday {
            get {
                return ResourceManager.GetString("strBirthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản xuất.
        /// </summary>
        public static string strBrand {
            get {
                return ResourceManager.GetString("strBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dung tích.
        /// </summary>
        public static string strCapacity {
            get {
                return ResourceManager.GetString("strCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã bảo mật.
        /// </summary>
        public static string strCaptcha {
            get {
                return ResourceManager.GetString("strCaptcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giỏ hàng.
        /// </summary>
        public static string strCart {
            get {
                return ResourceManager.GetString("strCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giỏ hàng của bạn đang trống.
        /// </summary>
        public static string strCartEmpty {
            get {
                return ResourceManager.GetString("strCartEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đổi mật khẩu.
        /// </summary>
        public static string strChangePassword {
            get {
                return ResourceManager.GetString("strChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn cần tư vấn ?.
        /// </summary>
        public static string strChatFacebook {
            get {
                return ResourceManager.GetString("strChatFacebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bỏ Lọc.
        /// </summary>
        public static string strClear {
            get {
                return ResourceManager.GetString("strClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã hàng.
        /// </summary>
        public static string strCode {
            get {
                return ResourceManager.GetString("strCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bộ sưu tập.
        /// </summary>
        public static string strCollection {
            get {
                return ResourceManager.GetString("strCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mầu sản phẩm.
        /// </summary>
        public static string strColor {
            get {
                return ResourceManager.GetString("strColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bình luận.
        /// </summary>
        public static string strComment {
            get {
                return ResourceManager.GetString("strComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to So sánh.
        /// </summary>
        public static string strCompare {
            get {
                return ResourceManager.GetString("strCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã xác nhận.
        /// </summary>
        public static string strConfirmCode {
            get {
                return ResourceManager.GetString("strConfirmCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận mật khẩu.
        /// </summary>
        public static string strConfirmPassword {
            get {
                return ResourceManager.GetString("strConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nội dung.
        /// </summary>
        public static string strContent {
            get {
                return ResourceManager.GetString("strContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiếp tục mua hàng.
        /// </summary>
        public static string strContinuesShoping {
            get {
                return ResourceManager.GetString("strContinuesShoping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa có tài khoản.
        /// </summary>
        public static string strCreateNewAccount {
            get {
                return ResourceManager.GetString("strCreateNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật.
        /// </summary>
        public static string strDate {
            get {
                return ResourceManager.GetString("strDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả.
        /// </summary>
        public static string strDescription {
            get {
                return ResourceManager.GetString("strDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết sản phẩm.
        /// </summary>
        public static string strDescriptionDetail {
            get {
                return ResourceManager.GetString("strDescriptionDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạm tính.
        /// </summary>
        public static string strEstimated {
            get {
                return ResourceManager.GetString("strEstimated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phí ship.
        /// </summary>
        public static string strFeeShipp {
            get {
                return ResourceManager.GetString("strFeeShipp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lọc.
        /// </summary>
        public static string strFilter {
            get {
                return ResourceManager.GetString("strFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lấy lại mật khẩu.
        /// </summary>
        public static string strForgotPassword {
            get {
                return ResourceManager.GetString("strForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quên mật khẩu ?.
        /// </summary>
        public static string strForgotYourPassword {
            get {
                return ResourceManager.GetString("strForgotYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giới tính.
        /// </summary>
        public static string strGender {
            get {
                return ResourceManager.GetString("strGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOTLINE.
        /// </summary>
        public static string strHotline {
            get {
                return ResourceManager.GetString("strHotline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ảnh.
        /// </summary>
        public static string strImage {
            get {
                return ResourceManager.GetString("strImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin đặt hàng.
        /// </summary>
        public static string strInforOrder {
            get {
                return ResourceManager.GetString("strInforOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin giao hàng.
        /// </summary>
        public static string strInforShipping {
            get {
                return ResourceManager.GetString("strInforShipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập địa chỉ của bạn.
        /// </summary>
        public static string strInputAddress {
            get {
                return ResourceManager.GetString("strInputAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập mã bảo mật.
        /// </summary>
        public static string strInputCaptcha {
            get {
                return ResourceManager.GetString("strInputCaptcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập email của bạn.
        /// </summary>
        public static string strInputEmail {
            get {
                return ResourceManager.GetString("strInputEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập tên của bạn.
        /// </summary>
        public static string strInputName {
            get {
                return ResourceManager.GetString("strInputName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập số điện thoại.
        /// </summary>
        public static string strInputPhone {
            get {
                return ResourceManager.GetString("strInputPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Còn hàng.
        /// </summary>
        public static string strInStock {
            get {
                return ResourceManager.GetString("strInStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn cần tư vấn ?.
        /// </summary>
        public static string strLabelChatFacebook {
            get {
                return ResourceManager.GetString("strLabelChatFacebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hãy đăng ký tài khoản để đọc các ấn phẩm của thư viện..
        /// </summary>
        public static string strLabelCreateNewAccount {
            get {
                return ResourceManager.GetString("strLabelCreateNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn đã có tài khoản xin vui lòng đăng nhập.
        /// </summary>
        public static string strLabelExistsAccount {
            get {
                return ResourceManager.GetString("strLabelExistsAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kết quả tìm kiếm cho.
        /// </summary>
        public static string strLabelResultSearch {
            get {
                return ResourceManager.GetString("strLabelResultSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Công nghệ mới.
        /// </summary>
        public static string strLatestNews {
            get {
                return ResourceManager.GetString("strLatestNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link liên kết.
        /// </summary>
        public static string strLinkConnect {
            get {
                return ResourceManager.GetString("strLinkConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập.
        /// </summary>
        public static string strLogin {
            get {
                return ResourceManager.GetString("strLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập bằng dịch vụ khác.
        /// </summary>
        public static string strLoginOther {
            get {
                return ResourceManager.GetString("strLoginOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thoát.
        /// </summary>
        public static string strLogout {
            get {
                return ResourceManager.GetString("strLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nam.
        /// </summary>
        public static string strMen {
            get {
                return ResourceManager.GetString("strMen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn đã đổi mật khẩu thành công!.
        /// </summary>
        public static string strMessageChangePasswordSuccess {
            get {
                return ResourceManager.GetString("strMessageChangePasswordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin vui lòng nhập mã xác nhận từ email..
        /// </summary>
        public static string strMessageClientResetPassword {
            get {
                return ResourceManager.GetString("strMessageClientResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin vui lòng xác nhận lại mật khẩu..
        /// </summary>
        public static string strMessageConfirmPassword {
            get {
                return ResourceManager.GetString("strMessageConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin vui lòng điền đầy đủ thông tin !.
        /// </summary>
        public static string strMessageContactForm {
            get {
                return ResourceManager.GetString("strMessageContactForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cảm ơn quý khách đã gửi thắc mắc. Chúng tôi sẽ trả lời trong thời gian sớm nhất. Trân trọng !.
        /// </summary>
        public static string strMessageContactSend {
            get {
                return ResourceManager.GetString("strMessageContactSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin vui lòng kiểm tra lại mã xác nhận..
        /// </summary>
        public static string strMessageErrorConfirmCode {
            get {
                return ResourceManager.GetString("strMessageErrorConfirmCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin vui lòng nhập email đã đăng ký !.
        /// </summary>
        public static string strMessageForgotPassword {
            get {
                return ResourceManager.GetString("strMessageForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin vui lòng điền email và mật khẩu.
        /// </summary>
        public static string strMessageLogin {
            get {
                return ResourceManager.GetString("strMessageLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chúng tôi đã gửi xác nhận tới email của bạn. Hãy đăng nhặp email và thay đổi mật khẩu mới..
        /// </summary>
        public static string strMessageSendNewPassword {
            get {
                return ResourceManager.GetString("strMessageSendNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thông tin cá nhân thành công.
        /// </summary>
        public static string strMessageUpdateInforSuccess {
            get {
                return ResourceManager.GetString("strMessageUpdateInforSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin vui lòng nhập email đăng ký và mật khẩu!.
        /// </summary>
        public static string strMessageUserChangePassword {
            get {
                return ResourceManager.GetString("strMessageUserChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Để tìm thấy Spa của Linh Linh vui lòng điền theo mẫu..
        /// </summary>
        public static string strMessShowroom {
            get {
                return ResourceManager.GetString("strMessShowroom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin tài khoản.
        /// </summary>
        public static string strMyAccount {
            get {
                return ResourceManager.GetString("strMyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên.
        /// </summary>
        public static string strName {
            get {
                return ResourceManager.GetString("strName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu mới.
        /// </summary>
        public static string strNewPassword {
            get {
                return ResourceManager.GetString("strNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký nhận tin.
        /// </summary>
        public static string strNewsletter {
            get {
                return ResourceManager.GetString("strNewsletter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu cũ.
        /// </summary>
        public static string strOldPassword {
            get {
                return ResourceManager.GetString("strOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đặt hàng.
        /// </summary>
        public static string strOrder {
            get {
                return ResourceManager.GetString("strOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã đơn hàng.
        /// </summary>
        public static string strOrderCode {
            get {
                return ResourceManager.GetString("strOrderCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày tạo.
        /// </summary>
        public static string strOrderDate {
            get {
                return ResourceManager.GetString("strOrderDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản phẩm (cũ nhất).
        /// </summary>
        public static string strOrderDateAsc {
            get {
                return ResourceManager.GetString("strOrderDateAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản phẩm (mới nhất).
        /// </summary>
        public static string strOrderDateDesc {
            get {
                return ResourceManager.GetString("strOrderDateDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lịch sử giao dịch.
        /// </summary>
        public static string strOrderHistory {
            get {
                return ResourceManager.GetString("strOrderHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn hàng.
        /// </summary>
        public static string strOrderList {
            get {
                return ResourceManager.GetString("strOrderList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên (A - Z).
        /// </summary>
        public static string strOrderNameAsc {
            get {
                return ResourceManager.GetString("strOrderNameAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên (Z - A).
        /// </summary>
        public static string strOrderNameDesc {
            get {
                return ResourceManager.GetString("strOrderNameDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá (thấp &amp;#187; cao).
        /// </summary>
        public static string strOrderPriceAsc {
            get {
                return ResourceManager.GetString("strOrderPriceAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá (cao &amp;#187; thấp).
        /// </summary>
        public static string strOrderPriceDesc {
            get {
                return ResourceManager.GetString("strOrderPriceDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái.
        /// </summary>
        public static string strOrderStatus {
            get {
                return ResourceManager.GetString("strOrderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quý khách đã gửi đơn hàng thành công !.
        /// </summary>
        public static string strOrderSuccess {
            get {
                return ResourceManager.GetString("strOrderSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Các bài viết khác.
        /// </summary>
        public static string strOtherPost {
            get {
                return ResourceManager.GetString("strOtherPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hết hàng.
        /// </summary>
        public static string strOutOfStock {
            get {
                return ResourceManager.GetString("strOutOfStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu.
        /// </summary>
        public static string strPassword {
            get {
                return ResourceManager.GetString("strPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanh toán.
        /// </summary>
        public static string strPayment {
            get {
                return ResourceManager.GetString("strPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanh toán khi nhận hàng.
        /// </summary>
        public static string strPaymentAddress {
            get {
                return ResourceManager.GetString("strPaymentAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanh toán qua Bảo Kim.
        /// </summary>
        public static string strPaymentBaoKim {
            get {
                return ResourceManager.GetString("strPaymentBaoKim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hướng dẫn thanh toán.
        /// </summary>
        public static string strPaymentGuide {
            get {
                return ResourceManager.GetString("strPaymentGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanh toán.
        /// </summary>
        public static string strPaymentMethod {
            get {
                return ResourceManager.GetString("strPaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanh toán qua Ngân Lượng.
        /// </summary>
        public static string strPaymentNganLuong {
            get {
                return ResourceManager.GetString("strPaymentNganLuong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình thức khác.
        /// </summary>
        public static string strPaymentOther {
            get {
                return ResourceManager.GetString("strPaymentOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chúc mừng quý khách đã thanh toán thành công !.
        /// </summary>
        public static string strPaymentSuccess {
            get {
                return ResourceManager.GetString("strPaymentSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin cá nhân.
        /// </summary>
        public static string strPersonalInformation {
            get {
                return ResourceManager.GetString("strPersonalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điện thoại.
        /// </summary>
        public static string strPhone {
            get {
                return ResourceManager.GetString("strPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tin tức.
        /// </summary>
        public static string strPost {
            get {
                return ResourceManager.GetString("strPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tin tức mới nhất.
        /// </summary>
        public static string strPostHot {
            get {
                return ResourceManager.GetString("strPostHot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bài viết đã xem.
        /// </summary>
        public static string strPostView {
            get {
                return ResourceManager.GetString("strPostView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá.
        /// </summary>
        public static string strPrice {
            get {
                return ResourceManager.GetString("strPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khoảng giá.
        /// </summary>
        public static string strPriceRange {
            get {
                return ResourceManager.GetString("strPriceRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản phẩm.
        /// </summary>
        public static string strProduct {
            get {
                return ResourceManager.GetString("strProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản phẩm nổi bật.
        /// </summary>
        public static string strProductHot {
            get {
                return ResourceManager.GetString("strProductHot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Các loại hình biệt thự.
        /// </summary>
        public static string strProductHotLabel {
            get {
                return ResourceManager.GetString("strProductHotLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best Seller.
        /// </summary>
        public static string strProductNew {
            get {
                return ResourceManager.GetString("strProductNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản phẩm khác.
        /// </summary>
        public static string strProductSame {
            get {
                return ResourceManager.GetString("strProductSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản phẩm đã xem.
        /// </summary>
        public static string strProductView {
            get {
                return ResourceManager.GetString("strProductView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng.
        /// </summary>
        public static string strQuantity {
            get {
                return ResourceManager.GetString("strQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký.
        /// </summary>
        public static string strRegister {
            get {
                return ResourceManager.GetString("strRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập lại.
        /// </summary>
        public static string strReset {
            get {
                return ResourceManager.GetString("strReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lấy lại mật khẩu.
        /// </summary>
        public static string strResetPassword {
            get {
                return ResourceManager.GetString("strResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đánh giá.
        /// </summary>
        public static string strReview {
            get {
                return ResourceManager.GetString("strReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best Seller.
        /// </summary>
        public static string strSale {
            get {
                return ResourceManager.GetString("strSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm kiếm.
        /// </summary>
        public static string strSearch {
            get {
                return ResourceManager.GetString("strSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy kết quả nào.
        /// </summary>
        public static string strSearchResult {
            get {
                return ResourceManager.GetString("strSearchResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiếp tục.
        /// </summary>
        public static string strSendOrder {
            get {
                return ResourceManager.GetString("strSendOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dịch vụ.
        /// </summary>
        public static string strService {
            get {
                return ResourceManager.GetString("strService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size sản phẩm.
        /// </summary>
        public static string strSize {
            get {
                return ResourceManager.GetString("strSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sắp xếp.
        /// </summary>
        public static string strSortBy {
            get {
                return ResourceManager.GetString("strSortBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá chỉ từ.
        /// </summary>
        public static string strStartingForm {
            get {
                return ResourceManager.GetString("strStartingForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yêu cầu lấy lại mật khẩu từ .
        /// </summary>
        public static string strSubjectConfirmForgotPassword {
            get {
                return ResourceManager.GetString("strSubjectConfirmForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn đặt hàng mới từ khách hàng.
        /// </summary>
        public static string strSubjectNewOrderClient {
            get {
                return ResourceManager.GetString("strSubjectNewOrderClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận đơn hàng.
        /// </summary>
        public static string strSubjectOrderConfirm {
            get {
                return ResourceManager.GetString("strSubjectOrderConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận thanh toán từ khách hàng .
        /// </summary>
        public static string strSubjectPaymentFromClient {
            get {
                return ResourceManager.GetString("strSubjectPaymentFromClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận thanh toán .
        /// </summary>
        public static string strSubjectPaymentStatus {
            get {
                return ResourceManager.GetString("strSubjectPaymentStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tóm tắt.
        /// </summary>
        public static string strSummary {
            get {
                return ResourceManager.GetString("strSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thành tiền.
        /// </summary>
        public static string strSumPrice {
            get {
                return ResourceManager.GetString("strSumPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT.
        /// </summary>
        public static string strTaxVAT {
            get {
                return ResourceManager.GetString("strTaxVAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiện ích.
        /// </summary>
        public static string strTestimonials {
            get {
                return ResourceManager.GetString("strTestimonials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng.
        /// </summary>
        public static string strTotal {
            get {
                return ResourceManager.GetString("strTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập hoặc email.
        /// </summary>
        public static string strUserName {
            get {
                return ResourceManager.GetString("strUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem online.
        /// </summary>
        public static string strViewOnline {
            get {
                return ResourceManager.GetString("strViewOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yêu thích.
        /// </summary>
        public static string strWishlist {
            get {
                return ResourceManager.GetString("strWishlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nữ.
        /// </summary>
        public static string strWoman {
            get {
                return ResourceManager.GetString("strWoman", resourceCulture);
            }
        }
    }
}
